"use client";

import { CheckCircle2, GripVertical, Pencil, Plus, Trash2 } from "lucide-react";
import { type DragEvent, type FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/client";
import type { IssueStatus } from "@/lib/supabase/database.types";

type Props = { initialStatuses: IssueStatus[]; issueCounts: Record<string, number>; loadError?: string };

export function StatusSettings({ initialStatuses, issueCounts, loadError }: Props) {
	const router = useRouter();
	const [statuses, setStatuses] = useState(initialStatuses);
	const [newName, setNewName] = useState("");
	const [editing, setEditing] = useState<IssueStatus | null>(null);
	const [editingName, setEditingName] = useState("");
	const [deleting, setDeleting] = useState<IssueStatus | null>(null);
	const [replacementId, setReplacementId] = useState("");
	const [draggedId, setDraggedId] = useState<string | null>(null);
	const [saving, setSaving] = useState(false);
	const [message, setMessage] = useState<string | null>(loadError ?? null);

	const showError = (error: unknown, fallback: string) => setMessage(error instanceof Error ? error.message : fallback);
	async function persistOrder(next: IssueStatus[]) {
		setSaving(true); setMessage(null);
		try { const { data, error } = await createClient().rpc("reorder_issue_statuses", { p_status_ids: next.map((status) => status.id) }); if (error || !data) throw error ?? new Error("Could not save the order."); setStatuses(data); router.refresh(); }
		catch (error) { showError(error, "Could not save the order."); } finally { setSaving(false); }
	}
	function move(id: string, direction: -1 | 1) { const index = statuses.findIndex((status) => status.id === id); const target = index + direction; if (target < 0 || target >= statuses.length || saving) return; const next = [...statuses]; [next[index], next[target]] = [next[target], next[index]]; void persistOrder(next); }
	function drop(event: DragEvent<HTMLDivElement>, targetId: string) { event.preventDefault(); if (!draggedId || draggedId === targetId || saving) return; const from = statuses.findIndex((status) => status.id === draggedId); const to = statuses.findIndex((status) => status.id === targetId); const next = [...statuses]; const [item] = next.splice(from, 1); next.splice(to, 0, item); setDraggedId(null); void persistOrder(next); }
	async function addStatus(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!newName.trim()) return; setSaving(true); setMessage(null); try { const { data, error } = await createClient().rpc("add_issue_status", { p_name: newName.trim() }); if (error || !data) throw error ?? new Error("Could not add the status."); setStatuses((current) => [...current, data]); setNewName(""); router.refresh(); } catch (error) { showError(error, "Could not add the status."); } finally { setSaving(false); } }
	async function renameStatus(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing || !editingName.trim()) return; setSaving(true); setMessage(null); try { const { data, error } = await createClient().rpc("rename_issue_status", { p_status_id: editing.id, p_name: editingName.trim() }); if (error || !data) throw error ?? new Error("Could not rename the status."); setStatuses((current) => current.map((status) => status.id === data.id ? data : status)); setEditing(null); router.refresh(); } catch (error) { showError(error, "Could not rename the status."); } finally { setSaving(false); } }
	async function markComplete(status: IssueStatus) { if (status.is_complete || saving) return; setSaving(true); setMessage(null); try { const { data, error } = await createClient().rpc("set_complete_issue_status", { p_status_id: status.id }); if (error || !data) throw error ?? new Error("Could not update the completion status."); setStatuses((current) => current.map((item) => item.id === data.id ? data : { ...item, is_complete: false })); router.refresh(); } catch (error) { showError(error, "Could not update the completion status."); } finally { setSaving(false); } }
	async function deleteStatus() { if (!deleting) return; const issueCount = issueCounts[deleting.id] ?? 0; if (issueCount && !replacementId) return setMessage("Choose where to move existing issues."); setSaving(true); setMessage(null); try { const { error } = await createClient().rpc("delete_issue_status", { p_status_id: deleting.id, p_replacement_status_id: replacementId || null }); if (error) throw error; setStatuses((current) => current.filter((status) => status.id !== deleting.id)); setDeleting(null); router.refresh(); } catch (error) { showError(error, "Could not delete the status."); } finally { setSaving(false); } }

	return <section className="mx-auto w-full max-w-3xl p-6 sm:p-8 lg:p-10"><p className="text-sm font-medium text-sky-600">Workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Status settings</h1><p className="mt-2 text-slate-500">Define the stages in your workflow and arrange them in the order work moves through them.</p>{message && <p className="mt-6 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700" role="alert">{message}</p>}
		<form className="mt-8 flex gap-3" onSubmit={addStatus}><Input onChange={(event) => setNewName(event.target.value)} placeholder="e.g. Ready for review" value={newName} /><Button disabled={saving || !newName.trim()} type="submit"><Plus />Add status</Button></form>
		<div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white">{statuses.map((status, index) => <div className="flex items-center gap-3 border-b border-slate-100 p-4 last:border-0" draggable={!saving} key={status.id} onDragEnd={() => setDraggedId(null)} onDragOver={(event) => event.preventDefault()} onDragStart={() => setDraggedId(status.id)} onDrop={(event) => drop(event, status.id)}><GripVertical aria-hidden="true" className="shrink-0 text-slate-400" /><div className="min-w-0 flex-1"><p className="font-medium text-slate-950">{status.name}</p><p className="mt-1 text-xs text-slate-500">{issueCounts[status.id] ?? 0} {(issueCounts[status.id] ?? 0) === 1 ? "issue" : "issues"}{status.is_complete ? " · Complete status" : ""}</p></div><div className="flex shrink-0 items-center gap-1"><Button aria-label={`Move ${status.name} earlier`} disabled={saving || index === 0} onClick={() => move(status.id, -1)} size="icon-xs" type="button" variant="ghost">↑</Button><Button aria-label={`Move ${status.name} later`} disabled={saving || index === statuses.length - 1} onClick={() => move(status.id, 1)} size="icon-xs" type="button" variant="ghost">↓</Button><Button aria-label={`Rename ${status.name}`} disabled={saving} onClick={() => { setEditing(status); setEditingName(status.name); }} size="icon-xs" type="button" variant="ghost"><Pencil /></Button><Button aria-label={`Mark ${status.name} as complete`} className={status.is_complete ? "text-emerald-700" : ""} disabled={saving || status.is_complete} onClick={() => void markComplete(status)} size="icon-xs" type="button" variant="ghost"><CheckCircle2 /></Button><Button aria-label={`Delete ${status.name}`} disabled={saving || status.is_complete || statuses.length === 1} onClick={() => { setDeleting(status); setReplacementId(""); }} size="icon-xs" type="button" variant="ghost"><Trash2 className="text-rose-600" /></Button></div></div>)}</div><p className="mt-3 text-xs text-slate-500">Drag rows to reorder them. Only one status may be marked complete.</p>
		{editing && <Dialog title="Rename status" onClose={() => setEditing(null)}><form onSubmit={renameStatus}><Input autoFocus onChange={(event) => setEditingName(event.target.value)} value={editingName} /><DialogActions cancel={() => setEditing(null)} saving={saving} submit="Save" /></form></Dialog>}
		{deleting && <Dialog title={`Delete ${deleting.name}?`} onClose={() => setDeleting(null)}><p className="text-sm text-slate-600">{(issueCounts[deleting.id] ?? 0) ? "Choose a status for its existing issues before deleting it." : "This status has no issues and can be removed."}</p>{(issueCounts[deleting.id] ?? 0) > 0 && <select className="mt-4 h-9 w-full rounded-lg border border-slate-200 bg-white px-2.5 text-sm" onChange={(event) => setReplacementId(event.target.value)} value={replacementId}><option value="">Choose a replacement</option>{statuses.filter((status) => status.id !== deleting.id).map((status) => <option key={status.id} value={status.id}>{status.name}</option>)}</select>}<DialogActions cancel={() => setDeleting(null)} saving={saving} submit="Delete status" destructive onSubmit={() => void deleteStatus()} /></Dialog>}
	</section>;
}

function Dialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-semibold text-slate-950">{title}</h2><Button onClick={onClose} size="xs" type="button" variant="ghost">Close</Button></div><div className="mt-4">{children}</div></div></div>; }
function DialogActions({ cancel, saving, submit, destructive, onSubmit }: { cancel: () => void; saving: boolean; submit: string; destructive?: boolean; onSubmit?: () => void }) { return <div className="mt-6 flex justify-end gap-2"><Button disabled={saving} onClick={cancel} type="button" variant="outline">Cancel</Button><Button disabled={saving} onClick={onSubmit} type={onSubmit ? "button" : "submit"} variant={destructive ? "destructive" : "default"}>{saving ? "Saving…" : submit}</Button></div>; }
